# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQMqODNLqyj1v2dZO8XE-m_FBGGCpcyY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans

df=pd.read_csv('Mall_Customers.csv')
print(df.head())

df.info()

df.describe()

df.shape

df.columns

df.isnull().sum()

plt.figure(figsize=(8,5))
plt.scatter(
    df['Annual Income (k$)'],
    df['Spending Score (1-100)']
)
plt.xlabel('Annual income')
plt.ylabel("Spending Score")
plt.title("Customer Distribution")
plt.show()

x=df[['Annual Income (k$)',
        'Spending Score (1-100)']]

x.head()

list=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(x)
  list.append(kmeans.inertia_)
print(list)
print(len(list))

plt.figure(figsize=(8,5))
plt.plot(range(1,11),list,marker='o')
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")
plt.show()

k=5
kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_kmeans=kmeans.fit_predict(x)
print(y_kmeans)

print(kmeans.cluster_centers_)

plt.figure(figsize=(10,6))

plt.scatter(
    x.iloc[y_kmeans==0,0],
    x.iloc[y_kmeans==0,1],
    label='Cluster 1'
)

plt.scatter(
    x.iloc[y_kmeans==1,0],
    x.iloc[y_kmeans==1,1],
    label='Cluster 2'
)

plt.scatter(
    x.iloc[y_kmeans==2,0],
    x.iloc[y_kmeans==2,1],
    label='Cluster 3'
)

plt.scatter(
    x.iloc[y_kmeans==3,0],
    x.iloc[y_kmeans==3,1],
    label='Cluster 4'
)

plt.scatter(
    x.iloc[y_kmeans==4,0],
    x.iloc[y_kmeans==4,1],
    label='Cluster 5'
)

plt.scatter(
    kmeans.cluster_centers_[:,0],
    kmeans.cluster_centers_[:,1],
    s=300,
    marker='X',
    label='Centroids'
)

plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Customer Segments")
plt.legend()
plt.show()

df['Cluster'] = y_kmeans
df.head()

df['Cluster'].value_counts()

df.groupby('Cluster').mean(numeric_only=True)

df.to_csv("Customer_Segments.csv",
          index=False)